// NativeTTSWrapper.idl : IDL source for NativeTTSWrapper
//

// This file will be processed by the MIDL tool to
// produce the type library (NativeTTSWrapper.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "sapi.idl";

[
	object,
	uuid(A74D7C8E-4CC5-4F2F-A6EB-804DEE18500E),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface INativeTTSWrapper : IDispatch{
};

[
	uuid(B8F4A8E2-9C3D-4A5E-8F7C-2D1B3E4F5A6B),
	version(1.0),
]
library NativeTTSWrapperLib
{
	importlib("stdole2.tlb");
	[
		uuid(E1C4A8F2-9B3D-4A5E-8F7C-2D1B3E4F5A6B)
	]
	coclass CNativeTTSWrapper
	{
		[default] interface INativeTTSWrapper;
	};

	[
		uuid(F2E8B6A1-3C4D-4E5F-8A7B-9C1D2E3F4A5B)
	]
	coclass OpenSpeechSpVoice
	{
		interface ISpVoice;
		[default] interface IDispatch;
	};
};
