// NativeTTSWrapper.idl : IDL source for NativeTTSWrapper
//

// This file will be processed by the MIDL tool to
// produce the type library (NativeTTSWrapper.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(A74D7C8E-4CC5-4F2F-A6EB-804DEE18500E),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface INativeTTSWrapper : IDispatch{
};

[
	uuid(88B9DB87-7A85-4088-AE32-074F55718967),
	version(1.0),
]
library NativeTTSWrapperLib
{
	importlib("stdole2.tlb");
	[
		uuid(A1B2C3D4-E5F6-4A5B-8C9D-1E2F3A4B5C6D)
	]
	coclass CNativeTTSWrapper
	{
		[default] interface INativeTTSWrapper;
	};
};
