on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
      - name: Set up Python 3.11.4
        uses: actions/setup-python@v4.7.1
        with:
          python-version: "3.11.4"
      - name: Install uv
        run: |
          python -m pip install uv
      - name: Install dependencies
        run: |
          uv venv
          uv sync --all-extras
          uv pip freeze  # Let's see what's actually installed
      - name: Verify installations
        run: |
          uv run python -c "import PyInstaller; print('PyInstaller version:', PyInstaller.__version__)"
          uv run python -c "import PySide6; print('PySide6 version:', PySide6.__version__)"
      - name: Replace Encryption Key in Multiple Files
        shell: powershell
        run: |
          $encryptionKey = "${{ secrets.CONFIG_ENCRYPTION_KEY }}"
          $filePaths = @("configure_enc_utils.py")
          foreach ($filePath in $filePaths) {
            if (Test-Path $filePath) {
              $fileContent = Get-Content $filePath
              $updatedContent = $fileContent -replace "YOUR_ENCRYPTION_KEY", $encryptionKey
              Set-Content $filePath -Value $updatedContent
              Write-Output "Replaced encryption key in $filePath"
            } else {
              Write-Output "File not found: $filePath"
            }
          }
        env:
          CONFIG_ENCRYPTION_KEY: ${{ secrets.CONFIG_ENCRYPTION_KEY }} 
      - name: Inject secrets into environment and encrypt config
        shell: bash
        run: |
          uv run python configure_enc_utils.py -use-env
        env:
          MICROSOFT_TOKEN: ${{ secrets.MICROSOFT_TOKEN }}
          MICROSOFT_REGION: ${{ secrets.MICROSOFT_REGION }}
          GOOGLE_CREDS_JSON: ${{ secrets.GOOGLE_CREDS_JSON }}
          MICROSOFT_TOKEN_TRANS: ${{ secrets.MICROSOFT_TOKEN_TRANS }}
          CONFIG_ENCRYPTION_KEY: ${{ secrets.CONFIG_ENCRYPTION_KEY }} 
      - name: Build Apps
        run: |
          uv run python -c "import site; print(site.getsitepackages()[0])"
          .\build_executable.bat
        env:
          MICROSOFT_TOKEN: ${{ secrets.MICROSOFT_TOKEN }}
          MICROSOFT_REGION: ${{ secrets.MICROSOFT_REGION }}
          GOOGLE_CREDS_JSON: ${{ secrets.GOOGLE_CREDS_JSON }}
          MICROSOFT_TOKEN_TRANS: ${{ secrets.MICROSOFT_TOKEN_TRANS }}
          MYAPP_VERSION: ${{ github.ref_name }}  
      - name: Verify Output Directory
        run: |
          dir Output
      - name: Upload Unsigned Installer
        uses: actions/upload-artifact@v4
        with:
          name: 'UnsignedInstaller'
          path: 'Output\AACSpeakHelper.exe'
